version: '3'

services:
  app:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite:///data/library.db
      - ENVIRONMENT=production
    restart: unless-stopped 